def menu():
    print("----------------")
    print("    PIZZERIA    ")
    print("----------------")
    print("Scegli una opzione")
    print("")
    print("1) Mostra listino")
    print("2) Mostra tutti gli ordini")
    print("3) Mostra ordini di un cliente")
    print("4) Nuovo cliente")
    print("5) Aggiungi una pizza a un ordine")
    print("6) Rimuovi una pizza da un ordine")
    print("7) Conto di un cliente")
    print("8) Incasso totale")
    print("9) Pizze ordinate senza duplicati")
    print("10) Pizze mai ordinate")
    print("11) Pizza piu ordinata")
    print("12) Cliente che spende di piu")
    print("0) Esci")
    