def stampa_menu():
    print("===================================================")
    print("1)  Mostra tutte le librerie")
    print("2)  Mostra i brani di un utente")
    print("3)  Aggiungi un brano a un utente")
    print("4)  Rimuovi un brano a un utente")
    print("5)  Aggiungi un nuovo utente")
    print("6)  Rimuovi un utente")
    print("7)  Cerca un brano e mostra chi lo possiede")
    print("8)  Statistiche di un utente")
    print("9)  Utente con più brani")
    print("10) Tutti gli artisti senza duplicati")
    print("11) Brani in comune tra due utenti")
    print("12) Brano più presente")
    print("13) Far vedere tutti")
    print("14) Sposta un brano da un utente a un altro")
    print("15) Ordina la libreria di un utente")
    print("16) Classifica artisti per numero di brani")
    print("0)  Esci")
    print("===================================================")